/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
      extend: {
          "colors": {
              "inverse-primary": "#ffb59d",
              "surface-container-lowest": "#ffffff",
              "inverse-on-surface": "#f3f0ef",
              "on-error": "#ffffff",
              "primary-container": "#ff6b35",
              "surface-container-low": "#f6f3f2",
              "tertiary": "#785900",
              "surface-container-highest": "#e5e2e1",
              "on-surface-variant": "#594139",
              "error-container": "#ffdad6",
              "inverse-surface": "#313030",
              "on-secondary-container": "#004a69",
              "on-tertiary": "#ffffff",
              "tertiary-fixed": "#ffdf9e",
              "on-secondary-fixed": "#001e2d",
              "error": "#ba1a1a",
              "on-tertiary-container": "#412f00",
              "outline-variant": "#e1bfb5",
              "primary-fixed-dim": "#ffb59d",
              "on-primary-fixed": "#390c00",
              "tertiary-container": "#c29200",
              "secondary-fixed-dim": "#83cfff",
              "surface-tint": "#ab3500",
              "secondary": "#00658d",
              "on-secondary": "#ffffff",
              "outline": "#8d7168",
              "primary-fixed": "#ffdbd0",
              "secondary-fixed": "#c6e7ff",
              "on-tertiary-fixed-variant": "#5b4300",
              "on-primary-container": "#5f1900",
              "on-primary-fixed-variant": "#832600",
              "on-background": "#1c1b1b",
              "tertiary-fixed-dim": "#fabd00",
              "primary": "#ab3500",
              "surface-container": "#f0eded",
              "surface-dim": "#dcd9d9",
              "surface": "#fcf9f8",
              "surface-container-high": "#eae7e7",
              "secondary-container": "#3dbeff",
              "surface-variant": "#e5e2e1",
              "surface-bright": "#fcf9f8",
              "on-tertiary-fixed": "#261a00",
              "background": "#fcf9f8",
              "on-error-container": "#93000a",
              "on-primary": "#ffffff",
              "on-surface": "#1c1b1b",
              "on-secondary-fixed-variant": "#004c6b"
          },
          "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
          },
          "spacing": {
              "xs": "4px",
              "margin": "20px",
              "base": "8px",
              "sm": "12px",
              "lg": "24px",
              "md": "16px",
              "xl": "32px",
              "gutter": "16px"
          },
          "fontFamily": {
              "h3": ["Montserrat"],
              "label-bold": ["Inter"],
              "body-md": ["Inter"],
              "h1": ["Montserrat"],
              "display": ["Montserrat"],
              "h2": ["Montserrat"],
              "label-xs": ["Inter"],
              "body-sm": ["Inter"],
              "body-lg": ["Inter"]
          },
          "fontSize": {
              "h3": ["20px", { "lineHeight": "1.3", "fontWeight": "600" }],
              "label-bold": ["14px", { "lineHeight": "1.2", "fontWeight": "600" }],
              "body-md": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }],
              "h1": ["32px", { "lineHeight": "1.2", "fontWeight": "700" }],
              "display": ["40px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "800" }],
              "h2": ["24px", { "lineHeight": "1.2", "fontWeight": "700" }],
              "label-xs": ["12px", { "lineHeight": "1.2", "fontWeight": "500" }],
              "body-sm": ["14px", { "lineHeight": "1.4", "fontWeight": "400" }],
              "body-lg": ["18px", { "lineHeight": "1.5", "fontWeight": "400" }]
          }
      }
  },
  plugins: [],
}
